import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/contanctus">ContanctUs</Link>
        </li>
        <li>
          <Link to="/error">Error</Link>
        </li>
        <li>
          <Link to="/accountinformationtwo">AccountinformationTwo</Link>
        </li>
        <li>
          <Link to="/accountinformationone">AccountinformationOne</Link>
        </li>
        <li>
          <Link to="/accountinformationthree">AccountinformationThree</Link>
        </li>
        <li>
          <Link to="/accountinformation">Accountinformation</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
